export const SET_ITEMS = 'SET_ITEMS';

export const ITEM_DELETED = 'ITEM_DELETED';
export const ITEM_CHECKED = 'ITEM_CHECKED';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const START_LOADING_CHECKMARK = 'START_LOADING_CHECKMARK';
export const STOP_LOADING_CHECKMARK = 'STOP_LOADING_CHECKMARK';

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';